### PR TITLE
13.0

### PR DESCRIPTION
**Pull request by sashko**

### CODE REVIEW

**Comment by sashko** [comment]
cherry-pick recent patches to 13.0

**Comment by tolkien-joh** [comment]
@sashko 

the series of patch for gstreamer may be acceptable.
about other patches, we have to check them in double.

I didn't face any build problem like you during meta-ivi 13.0 build.
after my vacation,
 I'll build meta-ivi 13.0 from scratch in my desktop PC (ubuntu 14.04 LTS) for sure.
and this test will be executed in another PC (ubuntu 16.04 LTS)

**Comment by gunnarx** [comment]
Restarting build-check after fixed build pipeline.

**Comment by tolkien** [comment]
Hi @sashko 

I met this issue during release of meta-ivi 12.0.1, and
fix it. review https://github.com/GENIVI/meta-ivi/commit/4a64b490832e07d207866d6ee2972eed439439a6
and give your opinion.

**Comment by tobsan** [comment]
@tolkien-joh any updates on this? I had the exact same issues as @sashko so this would be nice to get merged.

**Comment by tobsan** [comment]
@tolkien-joh is there something stopping this PR from being merged? It would be nice having these settings upstream (as in meta-ivi) instead of locally in every layer that tries to use it everywhere.

**Comment by slawr** [comment]
@tobsan I agree this PR has been open too long. You maybe saw in the Genivi newsletter that went out this week that after a long contribution Wind River no longer provide the Baseline maintainer and that we are canvassing for a replacement. In the meantime the GDP team will pick up the slack on a best effort basis. At the moment they are necessarily concentrating on the GDP-13 release. So please bear with us a while longer, whilst we catch up.

@gunnarx and I discussed the open PRs in this weeks BIT call. We recognise that currently the Master and G13 branches are not equivalent when they should be. This PR will be a big help in making that happen.

Thanks

Steve
BIT Lead

**Comment by tobsan** [comment]
@slawr ah yes, I did saw that, thanks.

I mostly wanted to make sure this PR isn't forgotten.

**Comment by slawr** [comment]
Understandable. It's in the task back log.

**Comment by gunnarx** [comment]
I hope we get GDP releases done tomorrow finally - after that I could take a look at aligning meta-ivi branches and make sure that open meta-ivi PRs are finally processed.

**Comment by gunnarx** [comment]
Starting today on this.

**Comment by gunnarx** [comment]
I did the work to bring relevant commits from master to 13.0.  Also a little work to check that master is up to date with commits from other maintenance branches.   I have not pushed the result yet because of some more testing, but I will rebased this PR on the new (coming) master and push it back, to get a rebuild.

(@sashko, be aware that this modifies your 13.0 branch)

**Comment by gunnarx** [comment]
It builds.  After comparing I've drawn the conclusion that these commits are appropriate for 13.0

**Comment by gunnarx** [comment]
I determined that all patches on master are also applicable for 13.0 (i.e. not changing compliance of 13.0 spec).

The current master is somewhat messy with a lot of merge commits, but the best step to get in sync now seems to be to fast-forward 13.0 to master now.  (At this point in time -- they may (will) eventually diverge in the future of course).

Thus, all the commits provided here are now merged to 13.0 and this can be closed.

**Pull request closed without merging**
