### PR TITLE
common-api-c++: Add dlt-daemon dependency

### PR DESCRIPTION
**Pull request by chbae**
Change dlt-daemon runtime dependency to build dependency
because of build error.

Signed-off-by: Changhyeok Bae changhyeok.bae@gmail.com

### CODE REVIEW

**Comment by tolkien-joh** [comment]
Hi @chbae 

because meta-ivi 10.0.1 is released in branch 10.0, and I'm preparing 11 branch for meta-ivi 11,
 I think it's is not good to merge this to master branch.

I'm worry about the conflict of patches later.

**Comment by tolkien-joh** [comment]
Hi @chbae 

it's better to see this recipe.

[0001-common-api-c-Arrange-recipes.zip](https://github.com/GENIVI/meta-ivi/files/370519/0001-common-api-c-Arrange-recipes.zip)

**Comment by chbae** [comment]
@tolkien-joh
Yes. it's fine to me. Should I change? or will you?

**Comment by tolkien-joh** [comment]
@chbae 

please, do it now.

**Pull request merged**
