### PR TITLE
bluez5: rebase patches for 5.50

### PR DESCRIPTION
**Pull request by sashko**
Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by frznlogic** [comment]
This fails to apply properly, see the build output from https://go.genivi.org/go/tab/build/detail/yocto-baseline-GITHUB-PR-qemuarm64/60/Build/1/init_and_bitbake: 

```
12:14:07.486 ERROR: bluez5-5.48-r0 do_patch: Command Error: 'quilt --quiltrc /var/lib/go-agent/pipelines/yocto-baseline-GITHUB-PR-qemuarm64/build/tmp/work/aarch64-poky-linux/bluez5/5.48-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
12:14:07.486 Applying patch 0001-plugins-Add-initial-code-for-service-plugin.patch
12:14:07.486 patching file Makefile.plugins
12:14:07.487 patching file configure.ac
12:14:07.487 Hunk #1 FAILED at 328.
12:14:07.487 1 out of 1 hunk FAILED -- rejects in file configure.ac
12:14:07.487 patching file plugins/service.c
12:14:07.487 Patch 0001-plugins-Add-initial-code-for-service-plugin.patch does not apply (enforce with -f)
12:14:07.491 ERROR: bluez5-5.48-r0 do_patch: Function failed: patch_do_patch
12:14:07.494 ERROR: Logfile of failure stored in: /var/lib/go-agent/pipelines/yocto-baseline-GITHUB-PR-qemuarm64/build/tmp/work/aarch64-poky-linux/bluez5/5.48-r0/temp/log.do_patch.82060
12:14:07.494 NOTE: recipe bluez5-5.48-r0: task do_patch: Failed
12:14:07.498 ERROR: Task (/var/lib/go-agent/pipelines/yocto-baseline-GITHUB-PR-qemuarm64/poky/meta/recipes-connectivity/bluez5/bluez5_5.48.bb:do_patch) failed with exit code '1'
```

**Comment by gunnarx** [comment]
Build check fail...   Patch not seem to apply cleanly to bluez on master, so I took a quick look just to take some load from @frznlogic who needs to prioritize finalizing a release.  

- If I'm not misreading, meta-ivi master has a README that says poky should be on commit 96fbd39ba, which implies it is building bluez 5.48 (and the build log also shows 5.48 being built).

- Current status is also that (the latest) poky:sumo is still on bluez-5.48, whereas poky:master (and thud) has bluez-5.50.  So I assume you are working on thud?

- Therefore, if you want to give patches for bluez 5.50 then the dependent layer (poky) need to be updated too which means you should also propose a change the commit hash listed in the README.

Once meta-ivi 14.50 (i.e. sumo based) is released, it should go to a maintenance branch, so then meta-ivi:master could be allowed to move ahead to thud.  (Of course @frznlogic can make that changeover anytime now)

**Comment by sashko** [comment]
Gentlemen, I'm sorry for not being clear. It was sent to `master`, because it is aimed to work with current `poky` `master` (future `thud`). Of course, I can make needed changes to `README.md`.

**Comment by frznlogic** [comment]
@sashko that's not how meta-ivi master works, the README states which version the branch is tracking and which git hash it is built with.

**Pull request closed without merging**
