### PR TITLE
MAINTAINERS: fix maintainer's email

### PR DESCRIPTION
**Pull request by sashko**
Signed-off-by: Oleksandr Kravchuk <dev@sashko.rv.ua>

### CODE REVIEW

**Comment by mirzak** [comment]
Is this workflow even valid, that is using "git send-mail". I thought changes come in trough PR requests on github? :)

**Comment by sashko** [comment]
@mirzak I guess some people prefer it the old school way :)

**Comment by slawr** [comment]
Gunnar and I were discussing a related point on a different PR from Oleksandr. I think this content comes from when the primary host for meta-ivi was yoctoproject.org and WR provided the maintainer. Gunnar was saying a review of the meta-ivi submission policy might be useful. Although of course that should be done with the current maintainer :) Even if they are happy still to receive patches via the ML it should mention github. Personally I think it would be nice to have some commonality with GDP as well.

That review shouldn't stand in the way of this PR though. Oscar is more likely to respond than Tolkien :)

**Comment by frznlogic** [comment]
I agree, this is not the way I've been working at least :). I much prefer PR's in github as a workflow to email based management.

**Comment by frznlogic** [comment]
I'll merge this for now.

**Pull request merged**
