### PR TITLE
Update capicxx

### PR DESCRIPTION
**Pull request by gunnarx**
When playing with the code generators I found that updates were pending for all runtimes and tools.  I'm would assume that semantic versioning indicates these are compatible and might be applied also on 14.x rocko/sumo

### CODE REVIEW

**Comment by gunnarx** [comment]
Seems OK.  The failure that is shown is for H3 build - it is tested for PRs now, but still needs #89 to be merged before it actually works.

**Comment by gunnarx** [comment]
I double-checked the versions and commits again.  I don't see any issues, so I think you could merge this @martin-ejdestig.  (Again, H3 error should be completely unrelated) 

I guess more of a question is if it should be backported to maintenance branches - we could decide on the next audio conference discussion I suppose.

**Review by gunnarx — COMMENTED** [review]
common-api-c++ (core): Update to 3.1.12.4:  View the diff [here](
https://github.com/GENIVI/capicxx-core-runtime/compare/008f6c11f5371e93c06b3ed337326008d2031084..2fd0625d21f1fa8e6a3adfc89ce9f381a4d33990)

EDIT: I don't see any risky incompatibilities (and of course the semantic versioning suggests that there should not be).  A seemingly relevant bugfix related to selective broadcasts, to deinitializing and destruction.... The CHANGES file shows it clearly.

**Comment by gunnarx** [comment]
Discussed with BIT team yesterday. We saw no major risks backporting this to sumo maintenance branch but Martin suggested to take a quick look at the source code diff. 

(The meta-ivi update is needed for a "fixed" sumo based GDP build, before it moves to thud, therefore the fix is needed on meta-ivi sumo branch).

Since we need this merged I am adding review comments with links to diffs!

**Review by gunnarx — COMMENTED** [review]
common-api-c++-dbus: Update to 3.1.12.7:
View the diff [here](
https://github.com/GENIVI/capicxx-dbus-runtime/compare/5f694be78a2520cbdea31e8ba82cb579ebf893f9..77fd3ae09034b6f7cb87be7fd77d08cf106f53cb)

Review: Compatibility with dbus 1.12.x.  (FYI: poky:sumo uses 1.12.2 and poky:thud uses 1.12.10)
CHANGES file describes various other bugfixes for special cases.  Overall there is of course _some_ risk of regression bugs (or that some software has depended on previous wrong behavior) but I don't see at least anything immediately this upgrade should cause problems.

**Review by gunnarx — COMMENTED** [review]
common-api-c++-someip: Update to 3.1.12.12:
View the diff [here](
https://github.com/GENIVI/capicxx-someip-runtime/compare/fcead99a9c35abdb5dc042213d0567b799d1991f..64f0cb0133b23ff13c48c377546cdaef45b3d9ce)

Review: A bit more changes here.  There are various bugfixes preventing concurrency bugs, one mentioned deadlock, etc.  I'd say this is worth upgrading and there is no obvious incompatibility caused, but for anyone who then updates the layer at least these links give the possibility for them to evaluate the result of that for their project (which must always be done anyway when updating components or layers in production)

**Comment by gunnarx** [comment]
OK we need this urgently in GDP so to guarantee that the variant exist I created a feature branch [sumo_capicxx_upgrade](https://github.com/GENIVI/meta-ivi/tree/sumo_capicxx_upgrade) for now.

**Comment by slawr** [comment]
I vote to merge. Just don't forget you need it on Sumo as well (currently this is on meta-ivi master which is on Thud).

**Comment by martin-ejdestig** [comment]
Apparently this breaks common-api-test in meta-ivi-test. E.g.:

```
build/tmp/work/core2-64-poky-linux/common-api-test/3.1.5-r1/common-api-test/E01HelloWorld/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.hpp:103:7: error: no matching function for call to 'CommonAPI::DBus::DBusGetAttributeStubDispatcher<v0::commonapi::examples::E01HelloWorldStub, CommonAPI::Version>::DBusGetAttributeStubDispatcher(const CommonAPI::Version& (v0::commonapi::examples::E01HelloWorldStub::*)(std::shared_ptr<CommonAPI::ClientId>), const char [3])'
     > E01HelloWorldDBusStubAdapterInternal<_Stub, _Stubs...>::getE01HelloWorldInterfaceVersionStubDispatcher(&E01HelloWorldStub::getInterfaceVersion, "uu");
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Trying to regenerate the common-api code found in meta-ivi-test/recipes-extended/common-api/common-api-test/common-api-test-3.1.5.tar.gz after downloading the generators matching revisions in this pull request using mk_src-gen.sh found in the archive does not change anything in E01HelloWorld test though. So I am a bit confused.

**Comment by martin-ejdestig** [comment]
But also, I am not sure what weight should be given to tests failing.

About half of the "suites"/component specific tests fail when testing on qemux86-64. The three common-api suites are three of the working ones though.

**Comment by martin-ejdestig** [comment]
> Trying to regenerate the common-api code found in meta-ivi-test/recipes-extended/common-api/common-api-test/common-api-test-3.1.5.tar.gz after downloading the generators matching revisions in this pull request using mk_src-gen.sh found in the archive does not change anything in E01HelloWorld test though. So I am a bit confused.

Sorry, relied on git for diff:ing and there are .gitignore:s in the relevant directories. Regenerated and updated archive. Building a new test image now.

**Comment by martin-ejdestig** [comment]
@gunnarx You can pull updated tests to put in this PR from here: martin-ejdestig/meta-ivi@abb249f73edca47cd6aa141c4110996d7112c6ca (branch name pr94_test_regen)

**Comment by gunnarx** [comment]
@martin-ejdestig Thanks, and asking the submitter to update is typically a good idea, but also feel free to update PRs if you know what you want to change.

(You can force-push the source branch if needed :-) As maintainer you have that capability (unless the PR submitter explicitly turned it off) and it has always been our custom to do it that way.  It's mentioned, perhaps not for meta-ivi but at least in the [GDP contribution guidelines](https://at.projects.genivi.org/wiki/display/GDP/GDP+Contribution+Process)

**Comment by gunnarx** [comment]
:+1:  :)

**Comment by martin-ejdestig** [comment]
Created #101 for sumo to run it through CI/CD.

**Pull request merged**
