### PR TITLE
vehicle-signal-interface: add recipe

### PR DESCRIPTION
**Pull request by sashko**
Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by martin-ejdestig** [comment]
@sashko This PR was discussed a bit on today's BIT meeting. We want it, but just curious why you need it.

Also, it is not built when building the image now. Could you add a packagegroup-vehicle-signaling, add vehicle-signal-interface to it and then add the group to the image?

**Comment by sashko** [comment]
> @sashko This PR was discussed a bit on today's BIT meeting. We want it, but just curious why you need it.
> 
> Also, it is not built when building the image now. Could you add a packagegroup-vehicle-signaling, add vehicle-signal-interface to it and then add the group to the image?

We want it because we would like to write some software that uses it. Since it's GENIVI project, I thought it would make sense to add the recipe to the layer that is specifically made for GENIVI components.

Sure, I'll create the packagegroup and add a new commit to the PR, but are you sure you want it as part of the image by default even though nothing is currently using it?

**Comment by slawr** [comment]
Thank you for your continued support of the project Oleksandr.

As an aside we should also consider what it means to have VSI in meta-ivi at runtime. Should it be started by default? Does that make sense, or is it something that is better specified in a wider distro that consumes meta-ivi? If yes how and with what setup (in a way that allows it to be modified)? 

I don't think that is anything that would be a blocker for the PR to be merged, but it is something that should be considered. Possibly as a next step.

**Comment by gunnarx** [comment]
Discussed today. Via @martin-ejdestig we received info that this is not immediately urgent to merge.  I'd rather merge the patch in the vehicle_signal_interface than carry the patch in the layer, so I'll try to do that and update the PR.

**Comment by slawr** [comment]
> As an aside we should also consider what it means to have VSI in meta-ivi at runtime. Should it be started by default? Does that make sense, or is it something that is better specified in a wider distro that consumes meta-ivi? If yes how and with what setup (in a way that allows it to be modified)?
> 
> I don't think that is anything that would be a blocker for the PR to be merged, but it is something that should be considered. Possibly as a next step.

Discussed in the BIT call today. VSI is a library, rather than a daemon. So no need for a default service to start it.

**Comment by sashko** [comment]
@slawr @gunnarx ping.

**Pull request merged**
