### PR TITLE
Audiomanager fix

### PR DESCRIPTION
**Pull request by tolkien-joh**

### CODE REVIEW

**Comment by tom--pollard** [comment]
Is the .patch file missing from this PR?

**Comment by tolkien-joh** [comment]
@tom--pollard 

sorry, I added it.

**Comment by slawr** [comment]
+1 for merge

**Comment by tolkien-joh** [comment]
this patch set is for AM 7.0,
but, current 11.0 branch uses AM 7.4.

abandon this patch.

**Pull request closed without merging**
