### PR TITLE
14.x sumo

### PR DESCRIPTION
**Pull request by sashko**

### CODE REVIEW

**Comment by sashko** [comment]
Builds are failing since they're based on rocko.

**Comment by gunnarx** [comment]
> Builds are failing since they're based on rocko.

All PRs share the same pipeline for testing them, so sometimes we end up having things set up for one older version, and it affects new PR tests (or vice versa).

Another note, this PR was sent to master and not to 14.x-sumo, but they are the same so it won't make a difference.  I set up the 14.x-sumo since you asked for it.  Now, it will really only make a difference when it becomes time to merge, but if it's pointed at the sumo-branch instead then it can be merged correctly from GitHub.

However, the build issue is neither of those things, IMHO.  Instead, the PR can update the commit hashes mentioned in the README so that the dependent layers (poky, meta-openembedded, meta-gplv2) become sumo-based.  The build uses the info from the README to set up those layers, so the PR build should take that into account if you update the README.

Good luck (and note there might be slow responses due to vacation)

**Comment by sashko** [comment]
Oh, right. Now PR is for 14.x-sumo. Thanks.

**Comment by gunnarx** [comment]
OK great, I added the README change from #76 to this PR and force-updated it, so that the build checks can run.

(Note that this force-push updates your branch at: sashko:14.x-sumo)

**Comment by sashko** [comment]
Do you need to retrigger build or something? The one posted under PR is still based on rocko.

**Comment by gunnarx** [comment]
Yeah, working on it... Might be just all build agents are busy.  I will check.

**Comment by gunnarx** [comment]
I added #77 which I think will manage the transition when the branch name changes in the README.

**Comment by gunnarx** [comment]
Some issues when I've been poking around the CI-system.  So might as well just add the script fix here instead and see if it works correctly... (another force-push update...).  Now it's finally rebuilding

**Comment by gunnarx** [comment]
Well... *now* it is properly rebuilding that is...  Sorry for the delay.  
I expect there will be integration issues -- yes, some weston patch does not apply? --
But at least now it is a sumo-based result to look at.

**Comment by sashko** [comment]
It's fine, I understand. Thanks for taking care of it.

**Comment by frznlogic** [comment]
Hi, 

I'm back from vacation. Nice to see some work on this happening during my vacation! Thank you very much :). 

I've had a look at the changes and continued working on top of it to get further stuff working (fixed weston, added LAYERSERIES_COMPAT to the layers, removed pigz from dlt-daemon as it caused build issues). 

Further issues I'm working on/identified so far is:

- vsomeip relies on an older version of boost and claims to be compatible with version 1.55 and higher. In the latest version in poky (1.66) some functions have been removed that we need to talk to the vsomeip developers about. 
- The removal of the dbus patches in 0651d3b56005513ac18ef1ddf9b1197f09f7f202 is wrong, it removes a bunch of functions that are required by common-api-c++-dbus_3.1.12 afaict. They need to be re-applied imho. 

I'll continue looking at the last bug today.

**Comment by frznlogic** [comment]
The dbus issue was solved upstream in the capicxx-dbus-runtime in this commit, https://github.com/GENIVI/capicxx-dbus-runtime/commit/77fd3ae09034b6f7cb87be7fd77d08cf106f53cb

I'm testing it now.

**Review by sashko — COMMENTED** [review]
I believe you forgot to change SRCREV

**Comment by frznlogic** [comment]
I've gotten everything to build now afaics. I've cleaned up a bit of the history on my part and am waiting for builds to go through now. it builds locally for me right now at least. I'll do some more testing soon but I think this is getting to a point where it can be pulled in.

**Comment by slawr** [comment]
Good work all and welcome back Oscar.

Good to hear its building. I have a pre-release of the R-Car YP 2.5 YBSP so with the news its building I'll try a sanity build and boot test soon. I would create a Go pipleline for it but I need to ask Gunnar some questions before building out the R-Car pipelines further.

Regarding the review request I'll try and get to it this week, but I am out Thursday and on holiday next week.

**Comment by frznlogic** [comment]
@slawr thank you :). And no worries, take the review when you have time. I'll run tests and try to bump some recipes while I'm at it though.

**Comment by frznlogic** [comment]
I was a bit premature, the meta-ivi-test build fails. I have some more fixes for that but got stuck on fixing vsomeip also. Apparently CMake in sumo changed to building via ninja by default, and also it's complaining about containing bad RPATH's. I haven't been able to solve that yet. 

The last horrible commit will be fixed/broken up properly ;).

**Comment by sashko** [comment]
@frznlogic you can fix rpath issue with:

```
do_install_append() {
    chrpath -d ${D}${libdir}/libfoo.so
}
```

**Comment by frznlogic** [comment]
@sashko thanks for the tip. Update incoming soon <tm>

**Comment by frznlogic** [comment]
Updated, -test images builds now as well, including vsomeip

**Comment by slawr** [comment]
I didn't manage to get to a build or review this week so I'll return to it when I get back from my holiday in a weeks time. Don't let that hold you up of course.

**Comment by frznlogic** [comment]
Alright, im pulling this in since it's to a branch...

**Pull request merged**
