### PR TITLE
persistence-client-library: Update to latest commit

### PR DESCRIPTION
**Pull request by gmacario**
Prevent segfaults when running test-fw.sh persistence-client-library

Reference: [BASE-37]

Signed-off-by: Gianpaolo Macario <gianpaolo_macario@mentor.com>

### CODE REVIEW

**Comment by gmacario** [comment]
My local build is successful

```
gmacario@ies-genbld01-ub16:/opt/GENIVI/my-ygb12/build$ bitbake test-image
Parsing recipes: 100% |###############################################################################################| Time: 0:02:16
Parsing of 1537 .bb files complete (0 cached, 1537 parsed). 2103 targets, 321 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.32.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-16.04"
TARGET_SYS        = "x86_64-poky-linux"
MACHINE           = "qemux86-64"
DISTRO            = "poky-ivi-systemd"
DISTRO_VERSION    = "12.0.0"
TUNE_FEATURES     = "m64 core2"
TARGET_FPU        = ""
meta
meta-yocto
meta-yocto-bsp    = "HEAD:5aa481dfedfd089f0d6e8a3bae1b84134d5dff4c"
meta-oe
meta-filesystems  = "HEAD:1efa5d623bc64659b57389e50be2568b1355d5f7"
meta-ivi
meta-ivi-bsp
meta-ivi-test     = "fix-base-37-v3:40ccc652d83128c8ee7a39bc9b46103d9b39a415"

Initialising tasks: 100% |############################################################################################| Time: 0:00:15
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: Tasks Summary: Attempted 3653 tasks of which 3325 didn't need to be rerun and all succeeded.
gmacario@ies-genbld01-ub16:/opt/GENIVI/my-ygb12/build$
```

**Comment by gmacario** [comment]
Launch runqemu

```
../meta-ivi/scripts/runqemu qemux86-64 test-image nographic
```

Login as root@qemux86-64, then run PCL tests

```
Yocto GENIVI Baseline (Poky/meta-ivi) 12.0.0 qemux86-64 ttyS0

qemux86-64 login: root
root@qemux86-64:~# /opt/tests/test-fw.sh persistence-client-library
##########
persistence-client-library
##########
[ number of tests: 3 ]
[ run_1 ] 4 PASSED, 15 FAILED
[ run_2 ] 5 PASSED, 5 FAILED
[ run_3 ]Failed to restart nodestatemanager-daemon.service: Unit nodestatemanager-daemon.service is not loaded properly: File exists.
See system logs and 'systemctl status nodestatemanager-daemon.service' for details.
[ PASSED ]
root@qemux86-64:~#
```

**Comment by gunnarx** [comment]
Since you created a newer PR, that one got built just now.  But thankfully we can retrigger any old build in Go-CD which I did now.  So now this PR #25 is rebuilding with its commits, and should report green hopefully.

**Comment by gunnarx** [comment]
Hmm, my comment on #27 seemed to have disappeared.
Anyway, it fits better here to explain why this PR first failed.

1. The name of the image changes with every release.  (It might be easier if we try to avoid that)
2. The PR build pipeline is set up to build a specific image name - in this case it was **miranda-image** - but most PRs (including yours) are towards the nostromo branch. 

Hence the failure 
03:18:55.411 ERROR: Nothing PROVIDES 'miranda-image'

as reported on the [previously failed build](https://go.genivi.org/go/tab/build/detail/meta-ivi-Yocto-QEMU_x86-64-GITHUB-PR/2/Build/2/init_and_bitbake)

I have now changed the pipeline to build **nostromo-image**

So now, PRs that are sent to meta-ivi targeted for miranda-image branches will fail instead, unless we make the pipeline smarter.  Should be quite easy but I don't think I'll work on that right now - possibly we could discuss with @tolkien-joh first before putting work into that.  Very soon almost all expected PRs will be for nostromo-image anyway.

By the way, I noticed that master branch is still on *miranda-image*.  I have suggested in the past that master should track the latest development (nowadays 12.0/nostromo).  Hope @tolkien-joh agrees.

**Comment by gmacario** [comment]
Thanks @gunnarx!

I realized that the previous build https://go.genivi.org/go/tab/pipeline/history/meta-ivi-Yocto-QEMU_x86-64-GITHUB-PR had failed because of timeout fetching poky.
Unfortunately I had no rights to retrigger the build on go.genivi.org, therefore I created https://github.com/GENIVI/meta-ivi/issues/27 just to make sure it was not due to a problem of my PR.

**Comment by gunnarx** [comment]
Makes sense that developers can retrigger this pipeline.  I adjusted this.

**Pull request merged**
