### PR TITLE
README: update dependency layers to latest revisions (Sumo branch)

### PR DESCRIPTION
**Pull request by sashko**
Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by gunnarx** [comment]
Thanks for this one, and #90.  Just one thing - since the baseline is required to be compliant with the GENIVI specifications, we normally check what has been changed before updating the included layers.  It is just a simple sanity check to see that nothing becomes "non-compliant" due to the upgrade.  I think it is rarely a problem and I would not really expect to see API breaking changes for example, within one openembedded branch, but it's worth a quick check.

For the meta-ivi baseline it has not been done fully, but I would like to start doing like GDP does, which is to include a short log of all the changes in the layer between the two hashes.  We could create a new script to make it easier...  

For GDP Here is an example of what the [commit message](https://github.com/GENIVI/genivi-dev-platform/commit/2414260fb4e7132fd067092e583abd40c3d43269) with shortlog looks like.
And [here is the script](https://github.com/GENIVI/genivi-dev-platform/blob/master/scripts/git-submodule-bump) that creates it (but it only works on the GDP submodules, so a new one would be needed here).

**Review by gunnarx — CHANGES_REQUESTED** [review]
Requesting a change to include shortlog as noted in the previous comment.

**Comment by gunnarx** [comment]
Can #90 be closed because this one is newer?  They modify the same layers, right?  Which one do you think we should aim for here?

**Comment by sashko** [comment]
@gunnarx #90 is for `rocko` and this one is for `sumo`.

**Comment by gunnarx** [comment]
Ah yes, I forgot about that... :)

**Review by gunnarx — APPROVED** [review]

**Comment by gunnarx** [comment]
Great, the short log looks good.  I could not see anything that stands out as being an issue for compliance either so let's merge it.

**Pull request merged**
