### PR TITLE
#99 for master

### PR DESCRIPTION
**Pull request by martin-ejdestig**
#99 for master.

### CODE REVIEW

**Comment by martin-ejdestig** [comment]
@slawr @gunnarx Do you think it is worth waiting for CI/CD for this or should I just merge it?

**Comment by slawr** [comment]
I think it should be safe. These are solid improvements to the CI build scripting from Gunnar and they would be useful on Master as well. 

An update will be needed when Thud support for R-Car is released (very soon) but I don't see that as a reason to hold back, but you could wait for that if you wished.

**Comment by gunnarx** [comment]
My reasoning would be that it needs build & test at some point.  

I don't think the merge to master is a major risk, and in the very unlikely event that it's buggy, it can be fixed on master **but** that only happens if master branch is built immediately after merge to notice  the problem... which also requires CI.  

So I would say let's either confirm manually or wait for CI to be up.

**Comment by gunnarx** [comment]
Hmm, guess I commented too late, I didn't realize.

**Pull request merged**
