### PR TITLE
README.md: Update poky commit to thud-20.0.0

### PR DESCRIPTION
**Pull request by gunnarx**
This is using the tagged/release commit of poky - thud.

Note:
- poky:thud branch has additional commits since the tag - we can try updating that separately
- meta-gplv2 was already at the latest thud.
- meta-openembedded also already at the latest thud.  As of today meta-openembedded also has additional commits on master that are not on thud, but those are presumably for "next".

### CODE REVIEW

**Comment by gunnarx** [comment]
OK, this PRs naturally has the same weston.ini conflict that we identified already in #79.  Is it the case also in #96 -- let's see.

**Comment by gunnarx** [comment]
Comment, please refer to #96 for the fix.

**Comment by martin-ejdestig** [comment]
@gunnarx I rebased to latest master and have a squash! commit on top. Since it is your name on the commit I'll let you squash it and tweak to your heart's content.

Thought about copying https://github.com/GENIVI/genivi-dev-platform/blob/master/meta-genivi-dev/poky/meta/recipes-graphics/wayland/weston/weston.ini and get rid of the sed:ing etc but I do not understand why that file looks the way it does. (E.g. why does it set `[ivi-shell] ivi-module=ivi-controller.so` instead of `[core] modules=ivi-controller.so` like weston upstream does.)

Anyway, that is something that can be dealt with later. Let's get this in so we can move on with thud... ?

**Comment by slawr** [comment]
Yeah would be good to get ~~this in~~ a conclusion on this now. It's becoming somewhat of a blocker for me as I need to either publish a meta-ivi-renesas for pre weston-conf poky/meta-ivi or post weston-conf. Not a lot of point to do the former. 

Update: I tried @martin-ejdestig updated commit introducing weston-conf to meta-ivi. It builds ok for R-Car but there is an install issue. In summary as meta-ivi has a higher layer priority than meta-ivi-renesas it's do_install comes along and installs the meta-ivi weston.ini last. There by overwriting any R-Car settings. I'll add some details on Slack.

We therefore need to consider handling of weston.ini over a variety of machines. Various ways of doing that including multiple ways to make the meta-ivi weston-conf.bbappend QEMU specific.

**Comment by martin-ejdestig** [comment]
@slawr Weird since this should mimic what was done before this thud bump (e.g. there was no QEMU specific handling in meta-ivi... right?). Not at work at the moment so can not check Slack. But did you add a weston-conf.bbappend for R-Car as well?

**Comment by slawr** [comment]
> 
> 
> @slawr Weird since this should mimic what was done before this thud bump (e.g. there was no QEMU specific handling in meta-ivi... right?). Not at work at the moment so can not check Slack. But did you add a weston-conf.bbappend for R-Car as well?

I'm using your amendment in this PR. Problem seems to be that of layers providing weston-conf meta-ivi is highest priority so your weston.ini "wins". Details including code and example in Slack.

R-Car YBSP for Thud follows poky model of introducing [weston-conf](https://github.com/renesas-rcar/meta-renesas/blob/thud-dev/meta-rcar-gen3/recipes-graphics/wayland/weston-conf.bbappend) for weston.ini handling. I've adopted meta-ivi-renesas to do the same.

**Comment by martin-ejdestig** [comment]
Strange. Do not understand why you did not have a conflict before then because weston.bbappend in meta-ivi created a weston.ini for all platforms.

Anyway, let's talk on Monday. Weekend has started! :tada: :cake: :smile: :)

**Comment by gunnarx** [comment]
Let's merge this into a feature branch just to test on all targets of GDP.  You can clean up (squash) first.

**Comment by slawr** [comment]
~~Added PR to Gunnar's branch to update wayland ivi-extension~~
Realized that was complicating the path to get this merged for Martin. So closed the PR in Gunnar's branch and replaced it with a simpler #108 to Master.

**Comment by gunnarx** [comment]
Branch check build was done manually ([build log](https://go.genivi.org/go/tab/build/detail/yocto-baseline-poky-thud_20.0-test/1/Build/1/init_and_bitbake)).  It was OK.   Note, however, that temporary pipeline might be deleted soon.

**Pull request merged**
