### PR TITLE
critical bug fix of PAS, PCO

### PR DESCRIPTION
**Pull request by tolkien-joh**

### CODE REVIEW

**Comment by guysagnes** [comment]
why are are taking some patches in the integration flow instead of setup the corresponding commit inside the recipes:
- https://github.com/GENIVI/meta-ivi/blob/master/meta-ivi/recipes-extended/persistence-administrator/persistence-administrator_1.0.5.bb
- https://github.com/GENIVI/meta-ivi/blob/master/meta-ivi/recipes-extended/persistence-common-object/persistence-common-object_1.0.3.bb

**Comment by tolkien-joh** [comment]
Hi Guy

because these patches are included in meta-ivi 10 and
 I think the version change of s/w packages after baseline release makes some people be confused,
I want to keep the version of s/w package of meta-ivi 10.

after applying the critical bug fix's patches of PAS may give same result with version up
 whereas PCO is not.

In meta-ivi 11, I will upgrade two s/w if possible.

thank you.

__
Yong-iL Joh, Sr.MTS, Wind River
mobile +82-10-6332-6692  skype tolkienj
1. 6. 30., 오후 6:35, Guy Sagnes 작성:

why are are taking some patches in the integration flow instead of setup the corresponding commit inside the recipes:
-   https://github.com/GENIVI/meta-ivi/blob/master/meta-ivi/recipes-extended/persistence-administrator/persistence-administrator_1.0.5.bb
-   https://github.com/GENIVI/meta-ivi/blob/master/meta-ivi/recipes-extended/persistence-common-object/persistence-common-object_1.0.3.bb

**Comment by socec** [comment]
Is this going to be merged?

**Comment by tolkien-joh** [comment]
It will be merged to meta-ivi 10 branch next Monday
if there is no objection.

__
Yong-iL Joh, Sr.MTS, Wind River
mobile +82-10-6332-6692  skype tolkienj

**Comment by socec** [comment]
By next Monday you mean 2016-07-11?

**Comment by tolkien-joh** [comment]
sorry, I have to do this week.

**Pull request merged**
